課題完了！
YukiYouda/meal_app pull request #1
Opened 2021-10-13 08:51 UTC by YukiYouda

確認よろしくおねがいします。

2021-10-13 11:33 UTC, kazu-taka requested changes
@YukiYouda 
コメントした部分の修正をお願いします:bow:

2021-10-13 11:33 UTC, kazu-taka commented on database/migrations/2021_10_10_181649_create_posts_table.php
> +            ->constrained()
@YukiYouda 
細かくて申し訳ないですが、`->constrained()`のインデント修正お願いします！

2021-10-13 11:33 UTC, kazu-taka commented on resources/views/posts/index.blade.php
> +                            @endif
@YukiYouda 
なるべくビューにはPHPのロジックを記述しないほうがよいので、コントローラーで計算して、ビューに渡すように修正お願いします:bow:
照会画面も同様に修正お願いします！

2021-10-13 11:33 UTC, kazu-taka commented on resources/views/posts/show.blade.php
> +            @endif
@YukiYouda 
こちらのインデントがずれているので、修正お願いします！

2021-10-13 11:33 UTC, kazu-taka commented on routes/web.php
> +Route::resource('posts.likes', LikeController::class)
@YukiYouda 
ネストしたルーティングいいですね✨

2021-10-13 20:53 UTC, kazu-taka commented on resources/views/posts/index.blade.php
> +                            @endif
@YukiYouda 
すみません！！
私の勘違いです！！
ここにベタ書きしても良いですし、モデルにアクセサを作成して、その中にここのロジックを移動し、$post->xxxxを呼び出したら差分を返すという感じにしてもOKです🙇‍♂️

2021-10-14 00:20 UTC, YukiYouda commented on resources/views/posts/index.blade.php
> +                            @endif
この部分が全然思いつかず、昨日の夜、数時間溶かしました😢

2021-10-14 01:36 UTC, kazu-taka reviewed
@YukiYouda 
問題ないのでマージしてOKです！！
時間使わせてしまって申し訳ございません🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2021-10-14 01:36 UTC, kazu-taka commented on app/Models/Post.php
> +    public function getTime($time)
@YukiYouda 
ビューの方から`created_at`を渡していますが、インスタンス内からだと、$this->created_atで参照可能です！
今回はこのままでOKですが、時間がある時に確認してみて下さい✨

2021-10-14 05:05 UTC, merged